float:
  any:
  - base_args: ['@metric']
    constructor: PGVectorIVFFlat
    disabled: false
    docker_tag: ann-benchmarks-pgvector_ivfflat_ours
    module: ann_benchmarks.algorithms.pgvector_ivfflat_ours
    name: pgvector_ivfflat_ours
    run_groups:
      lists-10:
        arg_groups: [{lists: 100}]
        args: {}
        query_args: [[1, 5, 10, 20, 40, 80, 100, 200]]