float:
  any:
  - base_args: ['@metric']
    constructor: CuvsIVFFlat
    disabled: false
    docker_tag: ann-benchmarks-cuvs_ivfflat
    module: ann_benchmarks.algorithms.cuvs_ivfflat
    name: cuvs_ivfflat
    run_groups:
      # 固定配置：lists=100, workers=20, gpu=true
      lists-100-workers-20-gpu:
        arg_groups: [{lists: 100, use_gpu: true, batch_size: 10000}]
        args: {}
        query_args: [[1, 5, 10, 20, 40]]
