float:
  any:
  - base_args: ['@metric']
    constructor: PGVectorIVFJLOurs
    disabled: false
    docker_tag: ann-benchmarks-pgvector_ivfjl_ours
    module: ann_benchmarks.algorithms.pgvector_ivfjl_ours
    name: pgvector_ivfjl_ours
    run_groups:
      # 固定配置：workers=20, gpu=true
      workers-20-gpu:
        arg_groups: [{num_workers: 20, use_gpu: true, batch_size: 5000}]
        args: {}
        query_args: [[1]]
