float:
  any:
  - base_args: ['@metric']
    constructor: PGVectorSingle
    disabled: false
    docker_tag: ann-benchmarks-pgvectorgpu
    module: ann_benchmarks.algorithms.pgvector_parallel
    name: pgvector_ivfflat_gpu
    run_groups:
      # 固定配置：lists=100, workers=20, gpu=true
      lists-100-workers-20-gpu:
        arg_groups: [{lists: 100, use_gpu: true, batch_size: 5000, index_type: ivfflat, version: Ours}]
        args: {}
        query_args: [[1, 5, 10, 20, 40]]
