float:
  any:
  - base_args: ['@metric']
    constructor: PGVectorOurs
    disabled: false
    docker_tag: ann-benchmarks-pgvector_ours
    module: ann_benchmarks.algorithms.pgvector_ours
    name: pgvector_ivfflat_ours
    run_groups:
      # 固定配置：lists=100, workers=20, gpu=true
      lists-100-workers-20-gpu:
        arg_groups: [{lists: 100, num_workers: 20, use_gpu: true, batch_size: 5000, index_type: ivfflat}]
        args: {}
        query_args: [[1, 5, 10, 20, 40]]
