float:
  any:
  - base_args: ['@metric']
    constructor: PGVectorIVFMulti
    disabled: false
    docker_tag: ann-benchmarks-pgvector_ivf_multi
    module: ann_benchmarks.algorithms.pgvector_ivf_multi
    name: pgvector_ivf_multi
    run_groups:
      # 固定配置：lists=100, workers=20, gpu=true
      lists-100-workers-20-gpu:
        arg_groups: [{lists: 100, num_workers: 20, batch_size: 5000, index_type: flat}]
        # arg_groups: [{lists: 100, num_workers: 20, batch_size: 5000, index_type: jl, enable_reordering: True, target_dim: 64}]
        args: {}
        query_args: [[1, 5, 10, 20, 40]]
