float:
  any:
  - base_args: ['@metric']
    constructor: PGVectorSingle
    disabled: false
    docker_tag: ann-benchmarks-pgvector_single
    module: ann_benchmarks.algorithms.pgvector_single
    name: pgvector_ivfflat_single
    run_groups:
      lists-10:
        arg_groups: [{lists: 100, indextype: ivfflat}]
        args: {}
        query_args: [[1, 5, 10, 20, 40]]
