float:
  any:
  - base_args: ['@metric']
    constructor: PGVectorIVFPQCuvs
    disabled: false
    docker_tag: ann-benchmarks-pgvector_ivfpq_cuvs
    module: ann_benchmarks.algorithms.pgvector_ivfpq_cuvs
    name: pgvector_ivfpq_cuvs
    run_groups:
      # 固定配置：lists=100, workers=20, gpu=true
      lists-100-workers-20-gpu:
        arg_groups: [{lists: 100, use_gpu: true, batch_size: 5000}]
        args: {}
        query_args: [[1, 5, 10, 20, 40]]
