float:
  any:
  - base_args: ['@metric']
    constructor: PGVectorIVFFlatMulti
    disabled: false
    docker_tag: ann-benchmarks-pgvector_ivfflat_multi_ours
    module: ann_benchmarks.algorithms.pgvector_ivfflat_multi_ours
    name: pgvector_ivfflat_multi_ours
    run_groups:
      lists-100-workers-4-gpu:
        arg_groups: [{lists: 100, num_workers: 4, use_gpu: true, batch_size: 1000}]
        args: {}
        query_args: [[1, 5, 10, 20, 40, 80, 100, 200]]
      
      lists-100-workers-8-gpu:
        arg_groups: [{lists: 100, num_workers: 8, use_gpu: true, batch_size: 1000}]
        args: {}
        query_args: [[1, 5, 10, 20, 40, 80, 100, 200]]
      
      lists-100-workers-4:
        arg_groups: [{lists: 100, num_workers: 4, use_gpu: false, batch_size: 1000}]
        args: {}
        query_args: [[1, 5, 10, 20, 40, 80, 100, 200]]
      
      lists-100-workers-8:
        arg_groups: [{lists: 100, num_workers: 8, use_gpu: false, batch_size: 1000}]
        args: {}
        query_args: [[1, 5, 10, 20, 40, 80, 100, 200]]
